[package]
name = 'batch_transfer'
version = '1.0.0'
upgrade_policy = "compatible"


[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'

[addresses]
owner = ""
